notifier: 
  method:                smtp
  address:               smtp.gmail.com
  port:                  587
  domain:                gmail.com
  user_name:             larry.testone@gmail.com
  password:              NzoDUsi89lMF
  authentication:        plain
  enable_starttls_auto:  true
  message:
    subject: piss_subject
    body: piss_body
    to:   larry.testone@gmail.com

retriever: 
 method:      imap
 address:     imap.googlemail.com
 port:        993
 user_name:   larry.testone@gmail.com
 password:    NzoDUsi89lMF
 enable_ssl:  true 
